# -*- coding: utf-8 -*-
"""Olutope

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSW8Z2F77hJxVfZKkkSc8FPBX1tOW0BF

# STUDENT PERFORMANCE
"""

import pandas as pd
df = pd.read_csv("student_performance_month1_upgraded.csv")
df.head()

df

df.shape

df.info()

df.isna().sum()

df.duplicated().sum()

df.describe()

df["internet_access"] = (
    df["internet_access"]
    .astype(str)
    .str.strip()
    .str.title()
)

df["internet_access"] = df["internet_access"].replace({
    "Y": "Yes",
    "N": "No"
})

df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

df.info()
df.isna().sum()
df.describe()