# -*- coding: utf-8 -*-
"""Olutope

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSW8Z2F77hJxVfZKkkSc8FPBX1tOW0BF

# STUDENT PERFORMANCE
"""

import pandas as pd
df = pd.read_csv("student_performance_month1_upgraded.csv")
df.head()

df

df.shape

df.info()

df.isna().sum()

df.duplicated().sum()

df.describe()

df["internet_access"] = (
    df["internet_access"]
    .astype(str)
    .str.strip()
    .str.title()
)

df["internet_access"] = df["internet_access"].replace({
    "Y": "Yes",
    "N": "No"
})

df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

df.info()
df.isna().sum()
df.describe()

# Handle missing values (with reasoning)
df["study_hours_per_day"] = df["study_hours_per_day"].fillna(
    df["study_hours_per_day"].median()
)

df["attendance_percent"] = df["attendance_percent"].fillna(
    df["attendance_percent"].median()
)

df["sleep_hours"] = df["sleep_hours"].fillna(
    df["sleep_hours"].median()
)

df["previous_term_score"] = df["previous_term_score"].fillna(
    df["previous_term_score"].mean()
)

df["parent_education"] = df["parent_education"].fillna(
    df["parent_education"].mode()[0]
)

df

# Fix data errors (assignments_completed_out_of_10)
df["assignments_completed_out_of_10"] = df[
    "assignments_completed_out_of_10"
].clip(0, 10)

df

# Handle age outliers (17–25)
df = df[(df["age"] >= 17) & (df["age"] <= 25)]

df

"""Feature Engineering"""

# Study Level
df["study_level"] = pd.cut(
    df["study_hours_per_day"],
    bins=[0, 2, 3, df["study_hours_per_day"].max()],
    labels=["Low", "Medium", "High"],
    include_lowest=True
)

df

# Attendance Level
df["attendance_level"] = pd.cut(
    df["attendance_percent"],
    bins=[0, 60, 80, 100],
    labels=["Low", "Medium", "High"],
    include_lowest=True
)

# Improvement Gap
df["improvement_gap"] = (
    df["exam_score"] - df["previous_term_score"]
)

df

"""EDA (Exploratory Data Analysis)"""

# Univariate Analysis
import matplotlib.pyplot as plt

plt.hist(df["exam_score"], bins=10)
plt.title("Exam Score Distribution")
plt.show()

plt.hist(df["study_hours_per_day"], bins=10)
plt.title("Study Hours Distribution")
plt.show()

plt.hist(df["attendance_percent"], bins=10)
plt.title("Attendance Distribution")
plt.show()

# Group Comparisons
df.groupby("gender")["exam_score"].mean()
df.groupby("study_level")["exam_score"].mean()
df.groupby("tutoring")["exam_score"].mean()
df.groupby("school_type")["exam_score"].mean()

# Relationship Checks
plt.scatter(df["study_hours_per_day"], df["exam_score"])
plt.title("Study Hours vs Exam Score")
plt.show()

plt.scatter(df["attendance_percent"], df["exam_score"])
plt.title("Attendance vs Exam Score")
plt.show()